title: "ProgrammingWolf"
email: sanmithadissanayke@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome To ProgrammingWolf
baseurl: "/" 
url: "https://ProgrammingWolf.github.io" 
github_username:  ProgrammingWolf

sass:
  sass_dir: _sass

icon: "C:\Users\user\Desktop\ProgrammingWolf\WIN_20211205_12_50_56_Pro-removebg-preview.png"
