title: "Pod 4.1.X"
email: sanmithadissanayke@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome To ProgrammingWolf
baseurl: "/" 
url: "https://ProgrammingWolf.github.io" 
github_username:  ProgrammingWolf

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
